class CantExtractCode(Exception):
    ...

class NetworkError(Exception):
    ...

class CantGetResponseFromAI(Exception):
    ...

class CantSaveCode(Exception):
    ...

class CantRunProgram(Exception):
    ...

class CantCompileProgram(Exception):
    ...